name: Build, test & push container image

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  gosec-scan:
    name: Gosec Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec-action@v1
        with:
          args: './...'

  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-24.04
    needs: gosec-scan
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bootcamp-sdso-backend:${{ github.sha }}